blog/urls.py
from django.urls import path

from blog.views import (
    BlogCreateView,
    BlogDeleteView,
    BlogDetailView,
    BlogListView,
    BlogUpdateView,
)
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path("home/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("home/", BlogListView.as_view(), name="home"),
    path("create_blog/", BlogCreateView.as_view(), name="create_blog"),
    path("home/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
    path("home/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
]

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    AddProductView,
    CatalogContactsView,
    CatalogDetailView,
    CatalogHomeView,
    CategoryListView,
    ProductDeleteView,
    ProductsByCategoryView,
    ProductUpdateView,
)

app_name = "catalog"

urlpatterns = [
    path("", CatalogHomeView.as_view(), name="home"),
    path("contacts/", CatalogContactsView.as_view(), name="contacts"),
    path(
        "product/<int:pk>/",
        cache_page(60)(CatalogDetailView.as_view()),
        name="product_info",
    ),
    path("add_product/", AddProductView.as_view(), name="add_product"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path(
        "category/<int:category_id>/products/",
        ProductsByCategoryView.as_view(),
        name="category_products",
    ),
    path("category_list/", CategoryListView.as_view(), name="category_list"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
]

catalog/models.py
from django.db import models
from django.db.models import BooleanField

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name="Наименование")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name="Наименование")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="images/", blank=True, null=True, verbose_name="Изображение"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name="Категория",
    )
    price = models.IntegerField(
        help_text="Введите цену продукта", verbose_name="Цена за покупку"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )
    publication_status = models.BooleanField(default=False)
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name"]
        permissions = [
            ("can_unpublish_product", "can_unpublish_product"),
        ]

catalog/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "price", "category", "image"]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update(
            {
                "class": "form-control",  # Добавление CSS-класса для стилизации поля
                "placeholder": "Введите название продукта",
            }
        )  # Текст подсказки внутри поля

        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание продукта"}
        )

        self.fields["image"].widget.attrs.update(
            {
                "class": "form-control",
            }
        )

        self.fields["category"].widget.attrs.update(
            {
                "class": "form-control",
            }
        )

        self.fields["price"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите стоимость"}
        )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        description = cleaned_data.get("description")

        if name.lower() and description.lower() in [
            "казино",
            "криптовалюта",
            "крипта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]:
            self.add_error("name", "запрещенное слово")
            self.add_error("description", "запрещенное слово")

    def clean_price(self):
        cleaned_data = super().clean()
        price = cleaned_data.get("price")

        if price is None:
            raise forms.ValidationError("Цена должна быть указана.")

        if price < 0:
            raise forms.ValidationError("Цена не может быть отрицательной.")

        return price

    def clean_image(self):
        cleaned_data = super().clean()
        image = cleaned_data.get("image")
        if image is None:
            raise forms.ValidationError("Изображение не было загружено")

        if image.size > 5 * 1024 * 1024:
            raise forms.ValidationError("Размер файла не должен превышать 5 МБ.")

        if image.name.endswith(("jpg", "jpeg", "png")):
            raise forms.ValidationError(
                "Недопустимый формат файла. Загрузите JPEG или PNG."
            )

        return image


class ProductModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["publication_status"]

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from catalog.models import Category, Product

from .forms import ProductForm, ProductModeratorForm
from .services import get_products_by_category, get_products_from_cache


class CatalogHomeView(ListView):
    model = Product
    template_name = "catalog/home.html"
    context_object_name = "products"

    def get_queryset(self):
        return get_products_from_cache()


class CatalogContactsView(View):
    def get(self, request):
        return render(request, "catalog/contacts.html")

    def post(self, request):
        name = request.POST.get("name")
        message = request.POST.get("message")
        return HttpResponse(f'Спасибо, {name}! Сообщение "{message}" получено.')


class CatalogDetailView(DetailView):
    model = Product
    template_name = "catalog/product_info.html"
    context_object_name = "product"


class AddProductView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/add_product.html"
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    template_name = "catalog/product_delete.html"
    success_url = reverse_lazy("catalog:home")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("product.can_unpublish_product"):
            return ProductModeratorForm
        raise PermissionDenied


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/add_product.html"
    success_url = reverse_lazy("catalog:home")


class ProductsByCategoryView(View):
    model = Category

    def get(self, request, pk):
        category = get_object_or_404(Category, id=pk)
        products = get_products_by_category(pk)

        return render(
            request,
            "catalog/category_products.html",
            {"category": category, "products": products},
        )


class CategoryListView(ListView):
    model = Category
    template_name = "catalog/category_list.html"
    context_object_name = "categorys"

catalog/templates/catalog/add_product.html
{% extends "catalog/base.html" %}

{% block title %}Добавить новый товар{% endblock %}

{% block content %}
<div class="container">
    <h1 class="display-4">Добавить новый товар</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Добавить товар</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}TopShop{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">TopShop</h5>
        {% include 'catalog/menu.html' %}
    </div>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                TopShop
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">О магазине</a></li>
                    <li><a class="text-muted" href="#">Пункты выдачи заказов</a></li>
                    <li><a class="text-muted" href="#">Бренды</a></li>
                    <li><a class="text-muted" href="#">Коллекции</a></li>
                    <li><a class="text-muted" href="#">Доставка</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Наша история</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/home.html'%}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for category in categorys %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ category.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ category.name }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ category.description|truncatechars:100 }}</li>
                    </ul>
                    <a type="button"  class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_info' category.id %}">Посмотреть</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_products.html
{% extends 'catalog/home.html'%}
{% block title %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">TopShop</h1>
    <p class="lead">Продукты в категории {{ category.name }}</p>
</div>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ product.description|truncatechars:100 }}</li>
                    </ul>
                    <a type="button"  class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_info' product.id %}">Посмотреть</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends "catalog/base.html" %}

{% block title %}Контакты - TopShop{% endblock %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Russia</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>23-76229483</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Москва,ул.Петровка,дом 2</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends "catalog/base.html" %}
{% load catalog_tags %}
{% block title %}Главная - TopShop{% endblock %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">TopShop</h1>
        <p class="lead">TopShop - магазин оригинальной одежды от известных брендов</p>
    </div>

    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.price }} руб</h1>
                        <img src="{{ product.image| media_filter }}" class="card-img-top" alt="{{ product.name }}">
                    <p class="text-start">{{ product.description|truncatechars:100 }}</p>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_info' product.id %}">Посмотреть</a>
                    {% if perms.product.can_unpublish_product or user == product.owner %}
                    <a href="{% url 'catalog:product_update' product.id %}" class="btn btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/menu.html
<nav class="ms-5">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:category_list' %}">Категории</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:add_product' %}">Новый товар</a>
    {% if user.is_authenticated %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
    {% else %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
    {% endif %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
</nav>

catalog/templates/catalog/product_delete.html
{% extends 'catalog/base.html' %}

{% block title %}Добавить новый товар{% endblock %}

{% block content %}
<div class="container">
        <h1 class="mb-4">Удалить пост </h1>
        <p>Вы уверены, что хотите удалить "{{ object.name }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'catalog:product_info' product.id %}" class="btn btn-primary">Отмена</a>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_info.html
{% extends 'catalog/base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="product-info">
    <h1>{{ product.name }}</h1>
    <p>Цена: {{ product.price }} руб.</p>
    <p>Описание: {{ product.description }}</p>
    <p>Категория: {{ product.category }}</p>
    <p>Создан: {{ product.created_at }}</p>
    <p>Изменен: {{ product.updated_at }}</p>
    {% if perms.product.can_unpublish_product or user == product.owner %}
    <a href="{% url 'catalog:product_update' product.id %}" class="btn btn btn-lg btn-block btn-outline-primary">редактировать</a>
    <a href="{% url 'catalog:product_delete' product.id %}" class="btn btn btn-lg btn-block btn-danger">удалить</a>
    {% endif %}
</div>
{% endblock %}